apiVersion: v1
kind: Service
metadata:
  name: todos
  labels:
    app: todos
spec:
  type: NodePort
  selector:
    app: todos
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos
spec:
  selector:
    matchLabels:
      app: todos
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
      - image: fouzo09/nodetodos
        name: todos
        ports:
        - containerPort: 5000
          name: todos
        env:
          - name: MONGO_URL
            value: mongodb://mongo:27017/todos
      imagePullSecrets:
        - name: regcred